### PR TITLE
set Action correctly on puts for updateItem

### PR DESCRIPTION
**Pull request by bohlander**

### CODE REVIEW

**Comment by mhart** [comment]
The Action is optional - it defaults to PUT - were you seeing problems with this?

**Comment by bohlander** [comment]
Didn't realize it was optional -- feel free to ignore. I was debugging some
issues with updateItem, Expected, and dynalite and thought this might be a
potential bug.

**Comment by mhart** [comment]
Hmmm, well dynalite doesn't support the new `ComparisonOperator` on `Expected` yet - could that be the issue? It's on my TODO list (that one in my head) :-)

**Comment by bohlander** [comment]
I'm actually using the old deprecated 'Exists' and 'Value'. The issue is
that I'm trying to use only Exists, without specifying Value in the Expects
clause.  This fails on validation, but I think AWS allows only specifying
Exists true, and not requiring you to say what value you expect.

I'll double check with dynamodb on AWS and see how it behaves there, and
try to submit a patch.

Thanks for all your work on both of these libraries. Use them a ton!

**Pull request closed without merging**
